// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace examapi.Models
{
    public partial class Answers
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("answer")]
        [StringLength(50)]
        [Unicode(false)]
        public string Answer { get; set; }
        [Column("qes_id")]
        public int QesId { get; set; }
        [Column("isTrue")]
        [StringLength(10)]
        [Unicode(false)]
        public string IsTrue { get; set; }

        [ForeignKey("QesId")]
        [InverseProperty("Answers")]
        public virtual Questions Qes { get; set; }
    }
}