// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace examapi.Models
{
    public partial class Exam
    {
        [Key]
        [Column("std_id")]
        public int StdId { get; set; }
        [Key]
        [Column("Test_id")]
        public int TestId { get; set; }
        [Column("degree")]
        public int? Degree { get; set; }

        [ForeignKey("StdId")]
        [InverseProperty("Exam")]
        public virtual Student Std { get; set; }
        [ForeignKey("TestId")]
        [InverseProperty("Exam")]
        public virtual Test Test { get; set; }
    }
}