// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace examapi.Models
{
    public partial class Test
    {
        public Test()
        {
            Exam = new HashSet<Exam>();
            Questions = new HashSet<Questions>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [Column("img")]
        [StringLength(50)]
        [Unicode(false)]
        public string Img { get; set; }

        [InverseProperty("Test")]
        public virtual ICollection<Exam> Exam { get; set; }
        [InverseProperty("Test")]
        public virtual ICollection<Questions> Questions { get; set; }
    }
}